### ISSUE TITLE
TypeError: Cannot read property 'swing' of undefined

### ISSUE THREAD

**Issue by naga-wb** [gdsmith/jquery.easing#42]
Hi,

I have installed jQuery and Jquery.easing modules in my projec but I am getting below error when i run the page.

 at /node_modules/jquery.easing/jquery.easing.js:22:28
  at /node_modules/jquery.easing/jquery.easing.js:15:13
at Object.<anonymous> (/node_modules/jquery.easing/jquery.easing.js:19:3)
at Module._compile (internal/modules/cjs/loader.js:1176:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
at Module.load (internal/modules/cjs/loader.js:1040:32)
at Function.Module._load (internal/modules/cjs/loader.js:929:14)
at Module.require (internal/modules/cjs/loader.js:1080:19)
at require (internal/modules/cjs/helpers.js:72:18)
at eval (webpack-internal:///jquery.easing:1:18)

I seriously dont know what the cause of this issue. 

Please help me to resolve this issue

**Comment by natanaelgonzales** [comment]
> Hi,
> 
> I have installed jQuery and Jquery.easing modules in a project but I am getting below error when run the page.
> 
> at /node_modules/jquery.easing/jquery.easing.js:22:28
> at /node_modules/jquery.easing/jquery.easing.js:15:13
> at Object. (/node_modules/jquery.easing/jquery.easing.js:19:3)
> at Module._compile (internal/modules/cjs/loader.js:1176:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
> at Module.load (internal/modules/cjs/loader.js:1040:32)
> at Function.Module._load (internal/modules/cjs/loader.js:929:14)
> at Module.require (internal/modules/cjs/loader.js:1080:19)
> at require (internal/modules/cjs/helpers.js:72:18)
> at eval (webpack-internal:///jquery.easing:1:18)
> 
> I seriously dont know what the cause of this issue.
> 
> Please help me to resolve this issue

Try to change your CDN for one like https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.js 
Slim version don't have what you need
